### PR TITLE
fix arginfo and build warnings

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by codemasher** [comment]
I remember [changing this here](https://github.com/codemasher/php-ext-xz/commit/6c6d327b59b69402eb7ecdb762d01b997ff45b4a) because it broke the build in Windows. I've checked with this PR and still getting `ext\xz\utils.c(32): error C2036: 'void *': unknown size` [...].

**Comment by remicollet** [comment]
Please try with new version

**Comment by codemasher** [comment]
That looks good! (tested with the php-8.0 dev branch)

**Comment by remicollet** [comment]
Perhaps worth a new version ?

I still like to check the read/write for stream, especially the error check, and the API in 7.4 (error return -1) but won't have time in the next days

**Comment by codemasher** [comment]
Yes, i'm going to tag a new release - i have no problem to wait a few more days as i'm no C expert and i appreciate your contributions!
One thing i'd like to do is to add Windows builds to CI but from what it looks it's... complicated. Do you perhaps know of a php extension repo that has already accomplished that for GitHub actions?

**Comment by cmb69** [comment]
See https://github.com/php/pecl-database-dbase/tree/master/.github/workflows (which uses https://github.com/cmb69/setup-php-sdk). There is no support for installing the dependency libraries yet (not even for the core dependencies), but in your case just fetching and unpacking liblzma might be sufficient for now.

**Comment by codemasher** [comment]
This is what i was looking for - thank you so much!

**Pull request merged**
