### PR TITLE
Fix uncompress issue and stream

### PR DESCRIPTION
**Pull request by remicollet**
1st commit

* handle error in xzdecode (bad XZ data) with test

2nd commit

* fix buffer management in stream
* add test to ensure stream are working (on some big file)
* add context options for level and memory (see test for example)

### CODE REVIEW

**Comment by codemasher** [comment]
Thank you! I wonder if someone can adopt it for PECL, like proposed in the internals tread linked in the readme?

**Comment by remicollet** [comment]
What about tagging a 1.1.2 ?

**Comment by codemasher** [comment]
As soon as i got the CI for Windows running - i'd like to include the .dll in the release without having to compile them on my own PC :)

**Comment by codemasher** [comment]
Sorry for the delay - I've tagged 1.1.2 now. I haven't found time and nerves yet to include automated windows builds.

**Pull request merged**
