### PR TITLE
check for error, and return to caller

### PR DESCRIPTION
**Pull request by remicollet**
Should be the last from me

### CODE REVIEW

**Comment by codemasher** [comment]
Thank you so much!

**Comment by remicollet** [comment]
Please wait a bit more, seems stream is totally broken (uncompress)

**Comment by codemasher** [comment]
sure, no problem!

**Comment by remicollet** [comment]
in short

Compression, ie `copy($in; "compress.lzma://$out") `, work
Decompression, ie `copy("compress.lzma://$in", $out) `, is broken

**Pull request merged**
